# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Application(object):
    def setupUi(self, Application):
        Application.setObjectName("Application")
        Application.resize(400, 250)
        self.widget = QtWidgets.QWidget(Application)
        self.widget.setGeometry(QtCore.QRect(90, 70, 212, 80))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_click = QtWidgets.QPushButton(self.widget)
        self.btn_click.setObjectName("btn_click")
        self.btn_click.clicked.connect(self.click_me)
        self.horizontalLayout.addWidget(self.btn_click)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Application)
        QtCore.QMetaObject.connectSlotsByName(Application)

    def click_me(self):
        myText = self.lineEdit.text()
        self.label.setText(myText)

    def retranslateUi(self, Application):
        _translate = QtCore.QCoreApplication.translate
        Application.setWindowTitle(_translate("Application", "Form"))
        self.btn_click.setText(_translate("Application", "Click Me"))
        self.lineEdit.setPlaceholderText(_translate("Application", "Please Enter Your Name"))
        self.label.setText(_translate("Application", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Application = QtWidgets.QWidget()
    ui = Ui_Application()
    ui.setupUi(Application)
    Application.show()
    sys.exit(app.exec())
