# Form implementation generated from reading ui file 'databasewindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc # Custom import

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_createDB = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_createDB.setFont(font)
        self.pushButton_createDB.setObjectName("pushButton_createDB")
        self.horizontalLayout_2.addWidget(self.pushButton_createDB)
        spacerItem = QtWidgets.QSpacerItem(17, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_connectDB = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_connectDB.setFont(font)
        self.pushButton_connectDB.setObjectName("pushButton_connectDB")
        self.horizontalLayout_2.addWidget(self.pushButton_connectDB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_username = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout_3.addWidget(self.lineEdit_username)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_4.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton_submitInfo = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_submitInfo.setFont(font)
        self.pushButton_submitInfo.setObjectName("pushButton_submitInfo")
        self.verticalLayout.addWidget(self.pushButton_submitInfo)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

       #connect signal
        #----------------------------------
        self.pushButton_createDB.clicked.connect(self.createDatabase)
        #---------------------------------- 
        
        #connect signal
        #----------------------------------
        self.pushButton_connectDB.clicked.connect(self.connectDatabase)
        #---------------------------------- 
        
        #connect signal
        #----------------------------------
        self.pushButton_submitInfo.clicked.connect(self.insertData)
        #---------------------------------- 

   #All code below is added by Ben
   #---------------------------------------
    def createDatabase(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password=""
            ) 
            
            cursor = mydb.cursor()
            dbname = self.lineEdit.text()
            
            cursor.execute("CREATE DATABASE {}".format(dbname))
            self.label_result.setText("Database {} created".format(dbname))
            
        except mc.Error as e:
            self.label_result.setText("Database creation fail")
            
    def connectDatabase(self):
        
        dbname = self.lineEdit.text()
        
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database=dbname
            )
            
            self.label_result.setText("There is a connection")
            
        except mc.Error as e:
            self.label_result.setText("Database connection fail")
            
    def insertData(self):
        
        dbname = self.lineEdit.text()
        
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database=dbname
            )
            
            mycursor = mydb.cursor()
            
            username = self.lineEdit_username.text()
            password = self.lineEdit_password.text()
            
            query = "INSERT INTO users (username, password) VALUES (%s,%s)"
            value = (username,password)
            
            mycursor.execute(query, value)
            
            mydb.commit()
            self.label_result.setText("Data inserted")
            
        except mc.Error as e:
            self.label_result.setText("Error inserting data")
#-----------------------------------------

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Database Name:"))
        self.pushButton_createDB.setText(_translate("Form", "Create Database"))
        self.pushButton_connectDB.setText(_translate("Form", "Database Connection"))
        self.label_2.setText(_translate("Form", "Username:"))
        self.label_3.setText(_translate("Form", "Password:"))
        self.pushButton_submitInfo.setText(_translate("Form", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
