# Form implementation generated from reading ui file 'databasewindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc # Custom inport

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        self.label_result = QtWidgets.QLabel(Form)
        self.label_result.setGeometry(QtCore.QRect(10, 200, 581, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 40, 271, 29))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(40, 110, 313, 32))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_createDB = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        
        self.pushButton_createDB.setFont(font)
        self.pushButton_createDB.setObjectName("pushButton_createDB")
        self.horizontalLayout_2.addWidget(self.pushButton_createDB)
        spacerItem = QtWidgets.QSpacerItem(17, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_connectDB = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        
        #connect signal
        #----------------------------------
        self.pushButton_createDB.clicked.connect(self.createDatabase)
        #----------------------------------
        self.pushButton_connectDB.setFont(font)
        self.pushButton_connectDB.setObjectName("pushButton_connectDB")
        self.horizontalLayout_2.addWidget(self.pushButton_connectDB)

        #connect signal
        #----------------------------------
        self.pushButton_connectDB.clicked.connect(self.connectDatabase)
        #----------------------------------
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
   #All code below is added by Ben
   #---------------------------------------
    def createDatabase(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password=""
            ) 
            
            cursor = mydb.cursor()
            dbname = self.lineEdit.text()
            
            cursor.execute("CREATE DATABASE {}".format(dbname))
            self.label_result.setText("Database {} created".format(dbname))
            
        except mc.Error as e:
            self.label_result.setText("Database creation fail")
            
    def connectDatabase(self):
        
        dbname = self.lineEdit.text()
        
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database=dbname
            )
            
            self.label_result.setText("There is a connection")
            
        except mc.Error as e:
            self.label_result.setText("Database connection fail")
#-----------------------------------------
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Database Name:"))
        self.pushButton_createDB.setText(_translate("Form", "Create Database"))
        self.pushButton_connectDB.setText(_translate("Form", "Database Connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
